name: Upload Image to DockerHub

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: uraimo/run-on-arch-action@v1.0.8
          id: runcmd
          with:
            architecture: armv7
            distribution: ubuntu18.04
            run: |
              uname -a
              docker build -t docker-chromium-armhf .
              docker tag docker-chromium-armhf  hthiemann/docker-chromium-armhf
              echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
              docker push hthiemann/docker-chromium-armhf
              docker logout
