name: Upload Image to DockerHub

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Build Docker Image
        run: docker buildx build --platform linux/arm/v6,linux/arm/v7 --output "type=image,push=false" -t docker-chromium-armhf .

      - name: Tag Docker Image
        run: docker tag docker-chromium-armhf  hthiemann/docker-chromium-armhf

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Docker Push
        run: docker push hthiemann/docker-chromium-armhf

      - name: Docker Logout
        run: docker logout
